### ISSUE TITLE
Optional error reporting for logical combinations

### ISSUE THREAD

**Issue by ghost** [pboettch/json-schema-validator#105]
Hello,

In current version class logical_combination reports generic error after evaluation of all variants of subschema. It would be nice to add an option to log errors from individual subschemas as well if overall validation fails.

**Comment by pboettch** [comment]
This was existing in the first version of the library, which was otherwise so much  worse.

The problem is that with the error message callback you'd get message of failing combination-items which would be difficult to understand.

And I assume furthermore you would not want the error messages of failing combination-items if another one would be successful. So we would need to filter.

I might try something.

**Comment by pboettch** [comment]
I tried something and I have it on a local branch.

**Comment by gabor-varga** [comment]
Hi @pboettch , did you ever revisit this issue on your local branch?

**Comment by pboettch** [comment]
Yes I still have it on local. Would you mind testing and using it to see whether it fills the needs. I have to say it's quite verbose and only human readable.

**Comment by pboettch** [comment]
I pushed an 'error-check'-branch which contains a change printing sub-schema errors if the logical-combination has failed.

**Comment by gabor-varga** [comment]
Thanks @pboettch , I will check it. I basically want to find a way to print meaningful error messages on validation error that lets the user debug their config. We have quite complex schemas with many `one_of`.

**Comment by EShirykalov** [comment]
Thank you  @pboettch , I will try to use and test it as well.

**Comment by iksemyonov** [comment]
Hi @pboettch, have there been there any updates on the issue since January? Have you considered merging the branch to master?

**Comment by pboettch** [comment]
It seems I forgot to push it.

**Comment by pboettch** [comment]
Done.

**Comment by pboettch** [comment]
https://github.com/pboettch/json-schema-validator/tree/error-check

**Comment by lpelerin** [comment]
Hi @pboettch, I've tested a bit your `error-check` branch and found it quite useful.
Do you plan on merging this to master?

**Comment by zecoaat** [comment]
Hi @pboettch,

I also checked the `error-check` branch, but the solution is not exactly what we were looking for.

I've found two issues:
* The additional information will be generated only for the first logical combination level.
E.g. if there is an `anyOf`, and inside it an another `anyOf`, the messages will be generated only for the first `anyOf`.
There will be no detailed error messages generated for the deeper `anyOf` levels. (Or for any logical combination types).
* For custom error handlers it is not possible to access the `pointer` and the `instance` informations about the error, since they will be all packed into the `message`.

I have a probosal for fixing these issues and have all of the logical combination error messages:
* fork:
https://github.com/zecoaat/json-schema-validator
* diff with upstream:
https://github.com/pboettch/json-schema-validator/compare/main...zecoaat:json-schema-validator:main

For the default error handler it works like earlier - only the root logical combination error will be thown.

However, if you install a custom error hander, you can get all the details about the various cases:
```
no subschema has succeeded, but one of them is required to validate. Type: anyOf, number of failed subschemas: 3
[combination: anyOf / case#0] no subschema has succeeded, but one of them is required to validate. Type: anyOf, number of failed subschemas: 2
[combination: anyOf / case#0] [combination: anyOf / case#0] instance is below minimum of 5
[combination: anyOf / case#0] [combination: anyOf / case#1] instance is not a multiple of 2.0
[combination: anyOf / case#1] unexpected instance type
[combination: anyOf / case#2] unexpected instance type
```

(You can find the schema used for this test in the fork-project in tests.)

Please review the changes and consider merging this fork into the upstream project.
Thank you in advance,
Jimmy

**Comment by pboettch** [comment]
@zecoaat Do not hesite to make a pull-request here! Your work's output looks nice.

**Comment by zecoaat** [comment]
@pboettch I created the pull request for the modifications:
https://github.com/pboettch/json-schema-validator/pull/310
