### ISSUE TITLE
Cmake configuration issue

### ISSUE THREAD

**Issue by manuelgavidia** [pboettch/json-schema-validator#111]
The **nlohmann_json_DIR** refered in the README.md is the installation directory or could be the source directory?

When using the variable **nlohmann_json_DIR** pointing to the directory clone of the source git nlohmann/json repository the cmake can't find the json.hpp header.

Context :

1. I have a super project where I added nlohmann/json and pboettch/json-schema-validator as submodules
1. the nlohmann/json package is not installed as only header files are needed
1. I got the same error setting nlohmann_json_DIR to the source directory or the nlohmann/json/include or nlohmann/json/single_include

**Comment by prince-chrismc** [comment]
If you call `add_subdirectory(nlohmann/json)` followed by `add_subdirectory(pboettch/json-schema-validator)` you should not need to play with `nlohmann_json_DIR`

**Comment by pboettch** [comment]
There is much too many ways to incorporate nlohmann::json and this library in a build.

Before debugging this again, I think I will throw it all out and just find `nlohmann/json.hpp` and users can hint it with a variable. That's all what's need actually.

But @prince-chrismc is right, no variable needs to be set in order to make the valiation build when it's a sub-directory.

**Comment by manuelgavidia** [comment]
Thank you @prince-chrismc  and @pboettch for the quick answer.
The @prince-chrismc answer worked.
