### ISSUE TITLE
Throw exceptions subclassed from json::exception?

### ISSUE THREAD

**Issue by RPGillespie6** [pboettch/json-schema-validator#37]
This library currently throws `std` exceptions such as `std::invalid_argument` and `std::out_of_range`. `nlohmann::json` *used* to throw these exceptions, but has since changed to throw exceptions subclassed from `json::exception` such as `json::invalid_argument` and `json::out_of_range`.

Would it be worthwhile to upgrade this library to also throw `json::` subclassed exceptions? It would simplify json-related `try/catch`, I think.

**Comment by pboettch** [comment]
Yeah, you're right. This library should use the same exception-style as nlohmann's.

In version 2 of this library, error handling will be configurable by the user, but default will be exceptions in nlohmann's style. If you propose an implementation I'd be delighted, because I haven't looked at the details of it and don't really know, what to do.

**Comment by pboettch** [comment]
A new version will be pushed to master which basically fixes most of the issues. During validation there are no exceptions anymore. It is up to the implementer to pass an error-handler-object. The default one will tell whether there was an error or not. 

For backward-compat there will be a throwing handler, which will throw at the first error seen.

It is up to the user to implement an error handler to his convenience.

**Comment by pboettch** [comment]
I'll close this issue as exceptions are not instrinsic to the library anymore.
