### ISSUE TITLE
Would it be possible to modify the structure of the library?

### ISSUE THREAD

**Issue by paercebal** [pboettch/json-schema-validator#65]
Hello,
I'm interested by this library, but it has a few impediments for its use, IMHO:
1 - It could be a header-only library, which would simplify use/inclusion into existing project
2 - It should be correctly namespaced. For example, nlohmann's json code is inside the namespace nlohmann, and also included by adding nlohmann as a prefix (e.g. #include <nlohmann/json.hpp>)

The rest (the application, and the tests) would remain untouched.

Is it something you would welcome? If yes, what would be the namespace? pboettch? I would strongly advise against polluting nlohmann's namespace (it would be better to simply contribute the validator to nlohmann's project)

Thanks,

**Comment by pboettch** [comment]
I'm not a big fan of making it header-only. Because the only advantage would be to simplify integration in another project (which is actually a good argument though). 

The real benefit of header-only for me is the give the compiler the whole picture of the library while compiling to do even more magic in regards to optimizations. But this won't do much for this library because of its dynamic allocation of validation objects.

What you could do as an intermediate solution is to include the .cpp in one of your .cpp files instead of linking with this library. Than you have complete control and don't need to use this project's CMakeLists.txt .

I would be delighted to have this project included in Niels' project, but I think it won't be accepted. 

Another point is the more than poor implementations of JSON-URIs which would need more attention.

Could you make a PR for the necessary changes to adapt the include path?

**Comment by paercebal** [comment]
I forked the project, and play with it to see what can be done.

I will come back to you with a proposition, and if needed, and way to do it gradually, and gracefully so no user will be impacted by the changes.

Thanks,

**Comment by pboettch** [comment]
Closing it for now. Feel free to re-open anytime.
