### ISSUE TITLE
Get version at runtime

### ISSUE THREAD

**Issue by xamix** [pboettch/json-schema-validator#83]
Hello,

I'm used to print all library version used in my program when it is launched.

However I could not find anything in your library to print your library version (something like 2.0.0 at the current state).

I'm missing something or it is just a miss?

Regards.

**Comment by pboettch** [comment]
It does not exist.

**Comment by xamix** [comment]
Do you mind to add it in the next 2.1.0?

It is convenient to have it. As an exemple you check against json nlohmann version in your code so maybe other want to rely on a specific version of your library. 🙂

**Comment by pboettch** [comment]
If you could make a proposal I'd love to review and integrate it.

**Comment by xamix** [comment]
Sure,

1) I will define something like that in CMake file:
PBOETTCH_SCHEMA_VALIDATOR_VERSION_MAJOR   2
PBOETTCH_SCHEMA_VALIDATOR_VERSION_MINOR   1
PBOETTCH_SCHEMA_VALIDATOR_VERSION_PATCH    0

2) Generate with CMake a separate header file like `json-schema-config.hpp` which will contain those defines and also helpers functions something like this:

`get_schema_validator_version_string()`
`get_schema_validator_version_major()`
`get_schema_validator_version_minor()`
`get_schema_validator_version_patch()`

And also let access to the define directly.

Later you can dd function to return supported feature somtehting like for example:

`get_minimum_supported_nlohmann_version()`
`get_support_binaray....`

If you are okay with that I will do it

**Comment by pboettch** [comment]
In CMake you already have the versions available via [PROJECT_VERSION_*]](https://cmake.org/cmake/help/v3.13/variable/PROJECT_VERSION.html#variable:PROJECT_VERSION), you can use that. So we don't need `PBOETTCH_SCHEMA_VALIDATOR_VERSION_*` in CMake.

Don't over-engineer it though. Defines are tricky, because you need to deliver them as a .h-file. That would mean, if not included in the json-schema.hpp, a second .h would need to be delivered. Maybe the json-schema.hpp could be generate with `configure_file()` and using `@VERSION@` in a json-schema.hpp.in-file.

Getting version at runtime requires functions/method. Those should static in the `json_schema_validator-`class or at least limited in the namespace.

Start with something simple and make a PR, after reviewing we can still add more features.

**Comment by xamix** [comment]
I have implemented something in #115
I used configure file `json-schema.hpp.in` to generate your header file `json-schema.hpp` at configure time.

**Comment by pboettch** [comment]
We are discussing an alternative impl at #139
